version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: bl35ch27@A123
      MYSQL_DB: mangadb

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bl35ch27@A123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
